USE [master]
GO

/****** Object:  Database [Testes]    Script Date: 12/12/2017 00:21:17 ******/
CREATE DATABASE [Testes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Testes', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Testes.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Testes_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Testes_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Testes] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Testes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Testes] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Testes] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Testes] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Testes] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Testes] SET ARITHABORT OFF 
GO

ALTER DATABASE [Testes] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Testes] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Testes] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Testes] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Testes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Testes] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Testes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Testes] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Testes] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Testes] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Testes] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Testes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Testes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Testes] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Testes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Testes] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Testes] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Testes] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Testes] SET RECOVERY FULL 
GO

ALTER DATABASE [Testes] SET  MULTI_USER 
GO

ALTER DATABASE [Testes] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Testes] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Testes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Testes] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Testes] SET  READ_WRITE 
GO

