USE [Testes]
GO

/****** Object:  Table [dbo].[URLShort]    Script Date: 12/12/2017 00:10:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[URLShort](
	[urlid] [int] IDENTITY(1,1) NOT NULL,
	[url] [varchar](100) NOT NULL,
	[urlcount] [int] NULL,
	[urlshort] [varchar](100) NOT NULL,
 CONSTRAINT [PK_URLShort] PRIMARY KEY CLUSTERED 
(
	[urlid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
